2anki/server

- package.json
- src/pages/upload-page.imba
- src/server/parser/deck.imba
- test/create_deck.imba
- yarn.lock
This is a breaking change so the video should be updated but merging for now and will look into recording a new YouTube video later.
> Merge development into master

- src/app.imba
- src/components/n2a-header.imba
- src/pages/features-page.imba
- src/pages/home-page.imba
- src/server/server.imba
Closes #73 (Document all supported features on the front page)
- I created a page listing all features supported by notion2anki
- Added a link to that on the homepage
- Added a link to the navbar
> Created features page

- src/pages/upload-page.imba
> Update font size selector

- src/server/templates/custom.css
- Change font sizes to relative units.
- Align text to left on the back of the card. (looks much more natural)
> Minor improvements in custom style

- src/components/n2a-header.imba
I added the twitch link to the header (on the left) - this is an experiment
Closes #159
> Twitch link

- CONTRIBUTING.md
I added:
- link to v2.imba.io
- link to GitHub repository of imba.io (v2 branch)
- link to vscode extension
- links to notion2anki and scrimba (for people who want to see projects made using Imba)
- Extra info: imba playground on Scrimba
- and an encouraging message
closes #184
> Add Imba to CONTRIBUTING.md

- CONTRIBUTING.md
- README.md
- package.json
- src/pages/contact-page.imba
- src/pages/upload-page.imba
- src/server/parser/deck.imba
- src/server/server.imba
- yarn.lock
I've decided to go with custom tracking events instead of GA tags 🤫
Should close #176 🥳
> Add custom tracking for GA

- src/components/n2a-footer.imba
> added r/notion2anki link

- src/genanki/create_deck.py
I changed the weird field names to be something more sensible.
Closes #102
> AField, BField → Front, Back

- src/genanki/create_deck.py
- src/server/service/generator.imba
Fixing the environment issues for windows. (At least for me)
> Fixing the environment issues

- src/pages/benefits-page.imba
Added mobile to the benefits page with the links to Anki Mobile and AnkiDroid.
Closes #146
> Add mobile to the benefits page

- package-lock.json
- package.json
- server/parser/deck.js
I´ve remodelt the replacement of striked Elements.  So no longer will nonstriked elements be removed due to the similarity to another striked Element
> fixed the removing of nonstriked Elements

- server/parser/ToggleList.js
- server/parser/deck.js
Edited the way clozed are treated so that Latex Formulas can be inserted
> Clozes treatment

- web/public/index.html
Hopefully it works as expected.
> web: add Warm Welcome

- .github/workflows/build.yml
- .github/workflows/server-tests.yml
- README.md
- web/src/components/UploadForm.tsx
- web/src/components/modals/DownloadModal.tsx
It was linking to the development branch for some reason.
> Fix the broken link to the mascot

- server/genanki/create_deck.py
- server/parser/DeckParser.ts
- server/parser/Note.ts
This also brings the Notion ids into the payload.
Closes: #275
> server: add emoji for reversing single toggle

- server/package-lock.json
- server/package.json
- web/src/components/UploadForm.tsx
It will trigger the conversion so you don't need to click **convert** again.
> Make it more clear that you can drop files

- web/src/pages/NotionConnectPage.tsx
> fix redirect for notion

- server/routes/auth/create-key.ts
Seeing errors for some reason.
> server: remove await and log

- web/src/components/Header.tsx
> web/header: add new add right below the nav

- web/src/components/Header.tsx
It was getting noisy up there.
> components/Header: reduce clutter

- web/src/components/FontSizePicker.tsx
- web/src/components/modals/SettingsModal.tsx
This gives them more control and granularity on the selection.
Closes: https://github.com/alemayhu/Notion-to-Anki/issues/289
> web: provide users with slider for picking font

- server/parser/DeckParser.ts
- server/parser/Settings.ts
- web/src/store/Options.ts
This has been requested a few times now so adding it.
Closes: https://github.com/alemayhu/Notion-to-Anki/issues/201
> server: web: add new card option for linking back to Notion page

- server/genanki/create_deck.py
- server/package-lock.json
- server/package.json
- server/parser/Settings.ts
- web/src/store/Options.ts
This is going to reduce the amount of duplicates for users.
> server: web: expose and recommend using Notion ID with Notion Link

- web/src/pages/Home.tsx
Reference: https://stackoverflow.com/questions/17838607/making-an-iframe-responsive
> web: fix responsive issues for the iframe

- web/src/components/VideoSection.tsx
- web/src/pages/Home.tsx
- web/src/pages/UploadPage.tsx
Not a good first video really.
> web: change order of tutorials

- web/src/components/Header.tsx
- web/src/components/modals/DownloadModal.tsx
They are not needed anymore. It will also make it straightforward to remove Bulma later.
> Reducing the number of buttons

- web/src/pages/UploadPage.tsx
> fix broken link

- web/public/index.html
- web/src/GlobalStyle.tsx
> web: center the top ad 

- .github/workflows/build.yml
- .github/workflows/server-tests.yml
- .gitignore
- Dockerfile
- server/package-lock.json
- server/package.json
- server/tsconfig.json
- web/package-lock.json
- web/package.json
- web/src/components/CTAButton.tsx
- web/src/components/Header.tsx
- web/src/pages/Home.tsx
Hopefully this is going to speed up the deployment process 🤞🏾
> Try out new base image

- Dockerfile
- web/package.json
- web/src/components/UploadForm.tsx
- web/src/pages/UploadPage.tsx
Following noteworthy changes: started redesigning the upload form. Not ready yet. Work in progress.
> Deploy the current next branch

- server/handlers/BlockHandler.ts
- server/package-lock.json
- server/package.json
- server/routes/upload.ts
- server/test/notion-api.ts
- web/public/index.html
- web/src/GlobalStyle.tsx
The experiment was successful but we are moving in a different direction.
> web: Remove Google Adsense

- README.md
> fix patreon image link

- server/serve.ts
> add handler for /pre-signup

- server/package-lock.json
- server/package.json
- server/routes/upload.ts
- web/src/components/NewBanner.tsx
Hopefully this fixes issue for some users.
> Minor bug fix

- server/handlers/error.ts
- server/package-lock.json
- server/package.json
- server/serve.ts
- web/package-lock.json
- web/package.json
- web/src/components/NewBanner.tsx
- web/src/index.tsx
- web/src/pages/PreSignupPage.tsx
There are some edge cases where we can miss the source map but I don't
mind. It's better to have some reporting than none. Also this can be
improved later. For now we want to track the server and client issues.
> get sentry error tracking mostly working

- web/src/App.tsx
- web/src/pages/DashboardPage.tsx
> setup dashboard page

- Dockerfile
- server/routes/upload.ts
- server/serve.ts
We are going in a new direction :-D The current limits imposed will be
removed in the future and the user will themselves decide when and if
uploads get deleted.
> server: switch to using the new media storage

- server/package-lock.json
- server/package.json
Uploads and workspace directory were missing earlier and caused the last deployment to fail. Triggering this now.
> Trigger new deployment

- server/routes/upload.ts
> server/upload: don't attempt to create the upload path

- Dockerfile
- server/serve.ts
This should resolve the last failures.
> Removing more directory sync

- server/package.json
- server/routes/upload.ts
- server/serve.ts
We want more control for later.
> Use environment variables for directories

- .github/workflows/build.yml
- .github/workflows/server-tests.yml
- .gitignore
- Dockerfile
- server/package-lock.json
- server/package.json
- server/routes/upload.ts
This will reduce the disk size issue on the server and provide users more control in the future.
> Finally using the spaces for all uploads

- server/package.json
It's defaulting to development.
> server: run migrations for production

- server/knexfile.ts
The other fields are being ignored.
> server: try using connection string for production

- server/package-lock.json
- server/package.json
> server: bump version

- server/knexfile.ts
- server/storage/db.ts
> Use new url db

- Dockerfile
> Dockerfile: remove previous migration command

- Dockerfile
> server/Dockerfile: try setting migrations dir

- README.md
- web/src/components/NewBanner.tsx
> Follow up to the dashboard deployment

- server/handlers/TokenHandler.ts
- server/lib/CrashReporter.ts
- server/migrations/20210923121705_uploads.js
- server/routes/upload.ts
- server/routes/users.ts
- server/server.ts
- web/src/components/forms/RegisterForm.tsx
- web/src/pages/DashboardPage.js
For this initial round we are just storing references to the filenames and keys. This only applies to users who are logged in. In a follow-up we will start uploading the data from the workspaces and track those in the uploads table as well.
> Start saving some of the produced user data

- Makefile
- web/src/components/modals/SettingsModal.tsx
- web/src/pages/PreSignupPage.tsx
As title says it on the server side we are moving the CSS file into the deck structure. This is only for the default one, the customizations are still happening like before. 
Also fixing some issues with the committ making sure we push out server changes before adding them into this history. 
Finally got around to fixing some of the spacing issues on the pre-signup page and more changes to come soon.
> Moving styling into the deck structure

- web/_redirects
The previous dev server is not supported.
> Redirect all upload requests on Netlify to main server

- netlify.toml
- web/public/index.html
Also pull in server changes to avoid using production bucket in development.
> Attempt x at handling the legacy stuff 

- README.md
> README: add Fortress as sponsor

- netlify.toml
This fixes a regression introduced in 823494096edd (inline the styling into the deck info, 2021-09-28).
> genanki: make sure we use the Notion styling by default

- web/src/components/Footer.tsx
Couldn't make sense of the react-app-rewired-test, hence manually tested changes.
Fixes: #395 
Screenshots
> Added fortress logo to footer

- web/src/components/ErrorMessage.tsx
- web/src/components/UploadForm.tsx
- web/src/pages/UploadPage.tsx
Getting too much feedback on this topic and not much we can do when Notion is producing these files.
> Clarify the corrupt zip file situation

- web/src/components/ErrorMessage.tsx
- web/src/components/UploadForm.tsx
This will help some new users who get stuck uploading these files.
> web: show users a message when they upload huge files

- web/src/lib/Backend.ts
Having some connection issues on my main account.
> server: ce72a9e28a95 (log oauth connection issues, 2021-12-25)

- README.md
- web/src/components/Dashboard/DefineRules.tsx
- web/src/components/UploadForm.tsx
- web/src/components/forms/LoginForm.tsx
- web/src/components/modals/SettingsModal.tsx
- web/src/lib/Backend.ts
- web/src/pages/LoginPage.tsx
- web/src/store/Options.ts
This was requested by one of the beta users.
Some misc things also going in
> Add toggle mode to block handler

- README.md
This makes it clearer and avoids misleading users who expect this to be
100% free with regards to server resources.
> docs: add more information about the free

- LICENSE.md
- README.md
- web/public/index.html
- web/src/components/Footer.tsx
Fixes Sonar security hotspot issues.
> refactor: use https instead of http

- web/src/components/Dashboard/DefineRules.tsx
This is only adding it for the Notion integration.
> feature: 8ac7e91bd876 (add support for toggle headings, 2022-03-06)

- .github/workflows/commits.yml
Related-to: https://github.com/alemayhu/2anki.net/issues/505
Reference: https://github.com/webiny/action-conventional-commits
> style: add github workflow for checking commit messages

- web/src/App.tsx
- web/src/lib/Backend.ts
- web/src/lib/interfaces/UserUpload.ts
- web/src/pages/Uploads/ListUploadsPage.tsx
- web/src/pages/Uploads/components/ActiveJobs.tsx
- web/src/pages/Uploads/hooks/useActiveJobs.tsx
- web/src/pages/Uploads/hooks/usePatreon.tsx
- web/src/pages/Uploads/hooks/useQuota.tsx
- web/src/pages/Uploads/hooks/useUploads.tsx
Wrestling with eslint issues locally so opening up draft for now.
> wip: providing more user feedback in the uploads overview

- web/src/components/forms/RegisterForm.tsx
Thanks to a user who reported via email.
> fix: Account sign up not working

- web/src/components/forms/NewPassword.tsx
Reset stopped working when we overwrote the default behaviour.
> fix: reset password submit

- README.md
add video which shows the current plan
> add strategy section

- server/lib/email/templates/convert-link.html
- server/lib/email/templates/convert.html
- server/lib/email/templates/reset.html
- server/lib/email/templates/verification.html
> refactor: update email templates

- .github/workflows/dependabot_automerge.yml
Reference:
https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-797125425
> chore: add workflow file for dependabot

- .github/workflows/commits.yml
- .github/workflows/deploy.2anki.net.yml
We have renamed from master to main.
> chore: use main branch in workflows

- .github/workflows/auto-bump-version.yml
this will hopefully eliminate the manual version bumping which is error prone.
> feat: add action for automatically bumping the version

- scripts/development.bash
- web/src/pages/Upload/components/DownloadButton.tsx
> feat: trigger download when ready 

- server/lib/notion/BlockHandler.test.ts
- server/lib/notion/BlockHandler.ts
- server/lib/notion/NotionAPIWrapper.ts
- server/lib/notion/_mock/MockNotionAPI.ts
- server/lib/notion/_mock/payloads/GetPageResponse/eb64d738c17b444ab9d8a747372bed85.json
- server/lib/notion/_mock/payloads/ListBlockChildrenResponse/31575d65-1936-49b7-94e3-3a3fd38d6039.json
- server/lib/notion/_mock/payloads/ListBlockChildrenResponse/37c9491b-f33a-4de7-bcd6-c0b31b3d6378.json
- server/lib/notion/_mock/payloads/ListBlockChildrenResponse/88eda78b-61f7-41b2-b3fc-fd21dec0b79f.json
- server/lib/notion/_mock/payloads/ListBlockChildrenResponse/b00061f6-3081-456c-9607-f4938071ad75.json
- server/lib/notion/_mock/payloads/ListBlockChildrenResponse/b50fbc67-b351-4c6d-895a-0a25b18debd3.json
- server/lib/notion/_mock/payloads/ListBlockChildrenResponse/e302139e-bc06-452b-b9ef-bf22ac12300b.json
- server/lib/notion/_mock/payloads/ListBlockChildrenResponse/eb64d738c17b444ab9d8a747372bed85.json
- server/lib/notion/_mock/payloads/ListBlockChildrenResponse/ed5a1a98-245b-40b8-83ad-498445ec95d3.json
- server/lib/notion/_mock/payloads/ListBlockChildrenResponse/fba1b499-6733-4c6c-aa2d-005fd09a8edb.json
- server/lib/notion/blocks/BlockHeadings.tsx
- server/lib/notion/blocks/lists/BlockColumn.tsx
- server/lib/notion/blocks/media/BlockBookmark/index.tsx
- server/lib/notion/helpers/getClozeDeletionCard.ts
- server/lib/notion/helpers/getColumn.ts
- server/lib/notion/helpers/getInputCard.ts
- server/lib/notion/helpers/isColumnList.ts
- server/lib/parser/ParserRules.ts
- server/lib/parser/WorkSpace.ts
- server/package-lock.json
- server/package.json
- web/src/pages/Search/components/DefineRules.tsx
Closes: https://github.com/alemayhu/2anki.net/issues/471
> feat: add basic support for using column lists

- server/lib/notion/BlockHandler.test.ts
- server/lib/notion/BlockHandler.ts
- server/lib/notion/helpers/getClozeDeletionCard.ts
- server/lib/notion/helpers/isTesting.ts
We will add proper support later.
> fix: prevent crash for equation blocks 

- web/src/components/NavigationBar/NavigationBar.tsx
It got removed for some reason.
> fix: show menu on mobile

- server/lib/notion/BlockHandler.test.ts
- server/lib/notion/BlockHandler.ts
- server/lib/notion/NotionAPIWrapper.ts
- server/lib/notion/blocks/BlockEquation.test.tsx
- server/lib/notion/blocks/BlockEquation.tsx
- server/lib/notion/blocks/BlockHeadings.tsx
- server/lib/notion/blocks/BlockParagraph.tsx
- server/lib/notion/blocks/lists/BlockToggleList.tsx
- server/lib/notion/helpers/isEquation.ts
- server/lib/notion/helpers/isHeading.ts
- server/lib/notion/helpers/isTesting.ts
- server/lib/notion/helpers/isText.ts
- server/lib/notion/helpers/isToggle.ts
- server/lib/notion/helpers/renderFront.tsx
- server/lib/notion/helpers/renderTextChildren.tsx
- server/routes/notion/convert/helpers/performConversion.ts
Closes: https://github.com/alemayhu/2anki.net/issues/209
Closes: https://github.com/alemayhu/2anki.net/issues/606
> feat: add support for block equation

- .sonarcloud.properties
- server/KnexConfig.ts
- server/genanki/fs_util.py
- server/lib/notion/BlockHandler.ts
- server/lib/notion/helpers/perserveNewlinesIfApplicable.ts
- server/lib/notion/helpers/renderTextChildren.tsx
- server/lib/parser/DeckParser.ts
- server/lib/parser/Settings.ts
- server/package-lock.json
- server/package.json
- server/server.ts
> feat: preserve newlines card option

- server/lib/notion/BlockHandler.ts
- server/lib/notion/blocks/lists/BlockBulletList.tsx
- server/lib/notion/blocks/lists/BlockColumn.tsx
- server/lib/notion/blocks/lists/BlockNumberedList.tsx
- server/lib/notion/blocks/lists/BlockToggleList.tsx
- server/lib/notion/blocks/utils.tsx
- server/lib/notion/helpers/getChildren.ts
- server/lib/notion/helpers/getListItems.tsx
- server/package-lock.json
- server/package.json
This will render the children better but there are still missing bits
for handling types correctly with indentation.
Related-to: https://github.com/alemayhu/2anki.net/issues/445
> feat: add children for bullet and numbered lists

- server/package-lock.json
- server/package.json
Pulling in 68dea52bf899 (fix: clear cookies on logout, 2022-05-15)
> chore: bump version

- server/lib/constants.ts
- server/package-lock.json
- server/package.json
- server/routes/users/index.ts
- server/server.ts
Also triggering new release for various form link fixes on the frontend.
> refactor: make the build directory configurable from environment

- server/lib/notion/helpers/getListItems.tsx
- server/package-lock.json
- server/package.json
- server/server.ts
- server/templates/custom.css
Closes: https://github.com/2anki/server/issues/632
Also fixed environment issue when testing locally and we are now changing the default styles. 
Pulling in changes from web https://github.com/2anki/web/pull/39
> fix: render block annotations in children

- server/package-lock.json
- server/package.json
```
npm version prerelease --preid=alpha
```
> chore(package): bump version

- server/lib/User/updatePassword.ts
- server/lib/email/EmailHandler.ts
- server/lib/misc/TokenHandler.ts
- server/lib/notion/BlockHandler.test.ts
- server/lib/notion/NotionConnectionHandler.ts
- server/lib/notion/_mock/MockNotionAPI.ts
- server/lib/notion/_mock/helpers/MockType.ts
- server/lib/notion/_mock/helpers/dataMockPath.ts
- server/lib/notion/_mock/helpers/getPayload.ts
- server/lib/notion/_mock/helpers/mockDataExists.ts
- server/lib/notion/_mock/helpers/savePayload.ts
- server/lib/notion/_mock/helpers/types.ts
- server/lib/notion/helpers/renderTextChildren.tsx
- server/lib/parser/ParserRules.ts
- server/lib/parser/Settings.ts
- server/package-lock.json
- server/package.json
- server/routes/notion/index.ts
Closes: https://github.com/2anki/server/issues/554
> refactor: remove all of the any usage

- README.md
the link was broken due to repository transfer from alemayhu to 2anki
> docs(README): update logo path

- .github/workflows/sentry.yml
- server/tsconfig.json
We want to identify potential regressions introduced.
> chore: add sentry release

- README.md
> docs(README): update the project name

- src/routes/upload/helpers/cleanDeckname.test.ts
- src/routes/upload/helpers/cleanDeckname.ts
Fixes an issue where file name gets lost.
> fix: remove emojis from file name header

- src/lib/anki/zip.ts
- src/lib/misc/file.ts
- src/lib/misc/getUploadLimits.test.ts
- src/lib/misc/getUploadLimits.ts
- src/routes/upload/helpers/handleUpload.ts
- src/routes/upload/index.ts
- src/routes/upload/upload.ts
This will preserve backwards compat for anonymous users.
> fix: ensure patrons can at least upload 1GB files

- package-lock.json
- package.json
Pulling in web changes
[refactor(pages/MyUploads): move styling into own file](https://github.com/2anki/web/pull/104/commits/9574752cd26b815e2d4794ab3c8e3827fb1a4708)
[9574752](https://github.com/2anki/web/pull/104/commits/9574752cd26b815e2d4794ab3c8e3827fb1a4708)
[feat: render favicon titles](https://github.com/2anki/web/pull/104/commits/ebe07f413aa43dc48082d29da961726b60ff949d)
[ebe07f4](https://github.com/2anki/web/pull/104/commits/ebe07f413aa43dc48082d29da961726b60ff949d)
[feat: do not show file size info for patrons](https://github.com/2anki/web/pull/104/commits/b97c83825e23926de9746aca3f00363ee58f6414)
[b97c838](https://github.com/2anki/web/pull/104/commits/b97c83825e23926de9746aca3f00363ee58f6414)
[refactor(MyUploads): start cleaning it …
> chore: bump version to 1.0.0-alpha.13

- package-lock.json
- package.json
> chore: v1.0.0-alpha.14

- package-lock.json
- package.json
- src/lib/anki/CardGenerator.ts
- src/lib/misc/ErrorHandler.tsx
- src/lib/notion/BlockHandler.ts
- src/lib/notion/NotionConnectionHandler.ts
- src/lib/parser/DeckParser.ts
- src/lib/parser/Settings.ts
- src/lib/storage/StorageHandler.ts
- src/routes/download/u/index.ts
- src/routes/notion/convert/helpers/performConversion.ts
- src/routes/notion/getDatabase.ts
- src/routes/notion/index.ts
- src/routes/rules/findRule.ts
- src/routes/settings/createSetting.ts
- src/routes/settings/deleteSetting.ts
- src/routes/settings/findSetting.ts
- src/routes/upload/deleteJob.ts
- src/routes/upload/deleteUpload.ts
- src/routes/upload/getActiveJobs.ts
- src/routes/upload/getUploads.ts
- src/routes/upload/helpers/handleUpload.ts
- src/routes/upload/helpers/registerUploadSize.ts
- src/routes/upload/helpers/sendBundle.ts
- src/routes/upload/index.ts
- src/routes/users/index.ts
- src/server.ts
Give the user a hint when there are no cards created based on their rules.
> fix: start addressing some of the top errors

- src/routes/upload/helpers/handleUpload.ts
Has to be deployed after this is merged in https://github.com/2anki/web/pull/126
> fix: properly encode the users deck name

- src/templates/alex_deluxe.css
- src/templates/alex_deluxe_basic_back.html
- src/templates/alex_deluxe_basic_front.html
- src/templates/alex_deluxe_cloze_back.html
- src/templates/alex_deluxe_cloze_front.html
- src/templates/alex_deluxe_cloze_style.css
> feat: update my custom templates

- src/lib/email/EmailHandler.ts
Experimenting with GitHub actions
> merge next into main

- src/lib/jobs/helpers/deleteOldUploads.ts
- src/lib/notion/helpers/isColumnList.ts
- src/lib/storage/StorageHandler.ts
- src/middleware/RequireAllowedOrigin.ts
- src/middleware/RequireAuthentication.ts
Closes: https://github.com/2anki/server/issues/554
> refactor: remove any usage

- src/lib/parser/DeckParser.test.ts
- src/lib/parser/DeckParser.ts
- src/lib/parser/helpers/findToggleHeadings.ts
- src/lib/parser/types.ts
Closes: https://github.com/2anki/server/issues/794
> feat: add support for toggle headings in HTML file upload

- package-lock.json
- package.json
> 1.0.0-alpha.18

- src/lib/notion/helpers/getPlainText.ts
- src/lib/notion/helpers/renderFront.tsx
- src/lib/parser/Settings/Settings.ts
- src/routes/notion/renderBlock.ts
Ref: https://github.com/2anki/web/pull/178
> feat(renderBlock): render the front

- src/lib/notion/NotionAPIWrapper.ts
- src/routes/notion/deleteBlock.ts
- src/routes/notion/index.ts
Will be used in the learn page
> feat: add endpoint for deleting blocks

- src/lib/notion/NotionAPIWrapper.ts
- src/lib/notion/types.ts
- src/routes/notion/createBlock.ts
- src/routes/notion/index.ts
Will be used for creating extracts.
> feat: add endpoint for creating new blocks

- package-lock.json
- package.json
Expose the learn page to patrons
> 1.0.0-alpha.20

- package-lock.json
- package.json
> Revert "chore(deps): bump axios from 0.21.4 to 1.0.0"

- package-lock.json
- package.json
https://github.com/2anki/web/pull/226
> v1.0.0-alpha.32

- src/middleware/RequireAuthentication.ts
- src/routes/users/index.ts
> feat: set the user id for sentry

- package-lock.json
- package.json
> chore: 1.0.0-alpha.36

- .husky/pre-commit
- package-lock.json
- package.json
- src/lib/anki/zip.tsx
- src/lib/misc/ErrorHandler.tsx
- src/routes/upload/helpers/getPackagesFromZip.ts
- src/routes/upload/helpers/handleUpload.ts
- src/server.ts
- src/templates/README.html
> fix: handle sub pages regardless of location

- package-lock.json
- package.json
- src/lib/anki/zip.tsx
- src/lib/parser/DeckParser.ts
- src/lib/storage/StorageHandler.ts
- src/routes/upload/helpers/getPackagesFromZip.ts
- src/routes/upload/helpers/handleUpload.ts
We are experiencing too many errors in production.
Closes: https://github.com/2anki/server/issues/722
Closes: https://github.com/2anki/server/issues/992
> fix: replace jszip for reading user uploaded ZIP files

- src/routes/users/index.ts
It's causing a pending request when requesting password forgotten link.
> fix: remove outdated user field verified

- .github/workflows/deploy.2anki.net.yml
Currently deployments are failing.
> chore: mark github workspace as safe

- package-lock.json
- package.json
> 1.0.0-alpha.41

- src/routes/settings/findSetting.ts
https://github.com/2anki/web/pull/299
> fix: set payload for settings

- README.md
No currently active sponsors on GitHub.
> docs(README): remove sponsors section

- package-lock.json
- package.json
- src/lib/parser/DeckParser.ts
This handles issue where cloze deletions are not detected.
> fix: perform deck cleaning post deck creation

- .github/workflows/deploy.2anki.net.yml
- package-lock.json
- package.json
> build: use main branch

- .github/workflows/deploy.2anki.net.yml
This reverts commit 6c04e5cd71e9d7dffe1db6ebf99ba0875764941a.
> Revert "build: use main branch"

- package-lock.json
- package.json
> 1.0.0-alpha.50

- src/controllers/UploadController.ts
Should resolve the following Sentry error:
> ReferenceError
>
> <anonymous>(UploadController)
>
> crypto is not defined
> fix: add crypto module for file hashing

- src/controllers/NotionController.ts
- src/services/NotionService/BlockHandler/BlockHandler.test.ts
- src/services/NotionService/BlockHandler/BlockHandler.ts
- src/services/NotionService/NotionAPIWrapper.ts
- src/services/NotionService/_mock/MockNotionAPI.ts
- src/services/NotionService/helpers/getColumn.ts
Fixes: https://github.com/2anki/2anki.net/issues/1213
> fix: do not request blocks for unsupported types

- src/lib/constants.ts
- src/lib/storage/jobs/ScheduleCleanup.ts
- src/lib/storage/jobs/helpers/deleteOldFiles.ts
- src/lib/storage/jobs/helpers/deleteOldUploads.ts
Increasing it due to some errors on missing files.
> fix(storage): run cleanup every hour

- src/lib/constants.ts
- src/lib/storage/jobs/ScheduleCleanup.ts
- src/lib/storage/jobs/helpers/deleteOldFiles.ts
- src/lib/storage/jobs/helpers/deleteOldUploads.ts
> Revert "fix(storage): run cleanup every hour"

- src/lib/parser/DeckParser.test.ts
- src/services/NotionService/BlockHandler/BlockHandler.test.ts
- src/test/configure-jest.ts
Reducing the amount of console.log since it's causing a timeout.
> test: Add setupTests function for configuring jest

- src/lib/parser/experimental/PlainTextParser/PlainTextParser.ts
> fix(PlainTextParser): check answers before use

- package-lock.json
- package.json
- src/services/NotionService/NotionAPIWrapper.ts
We already handle adding emojis.
> fix: disable emoji for downloads titles

- jest.config.js
```
Executed in   35.98 secs    fish           external
usr time  336.41 secs  192.00 micros  336.41 secs
sys time   48.36 secs  683.00 micros   48.36 secs
```
```
Executed in    5.98 secs    fish           external
usr time   21.76 secs  194.00 micros   21.76 secs
sys time    5.31 secs  493.00 micros    5.31 secs
```
> test: speed up tests

- src/lib/error/sendError.ts
- src/test/configure-jest.ts
Changes to only get compact test result output.
- refactor: Improve error handling in sendError function
- test: silence more of the various console calls
> test: reduce logging in the tests

- .github/workflows/deploy.2anki.net.yml
We are using a new server now.
> chore(github): update the deployment script

- src/lib/storage/jobs/helpers/runCleanup.ts
> Revert "chore: add check env for skipping cleanup"

- src/lib/parser/exporters/embedFile.ts
Close: https://github.com/2anki/2anki.net/issues/1133
Related-to: https://github.com/2anki/2anki.net/issues/901
> fix(embedFile): improve the file retrieval from the payload

- package-lock.json
- package.json
- src/lib/anki/getDeckFilename.test.ts
- src/lib/anki/getDeckFilename.ts
- src/lib/anki/zip.tsx
- src/lib/parser/DeckParser.ts
- src/lib/parser/experimental/FallbackParser.ts
- src/lib/storage/checks.ts
related-to: https://github.com/2anki/2anki.net/issues/1291
> feat: convert csv to apkg

- README.md
> docs: remove twitter handle

- src/lib/parser/DeckParser.ts
Closes: https://github.com/2anki/2anki.net/issues/1303
Closes: https://github.com/2anki/2anki.net/issues/1292
> fix: handle indented toggles

- .eslintrc.js
- src/controllers/UploadController.test.ts
- src/controllers/UploadController.ts
- src/data_layer/NotionRespository.ts
- src/data_layer/UploadRespository.ts
- src/services/NotionService/NotionService.ts
- src/services/UploadService.ts
Closes: https://github.com/2anki/2anki.net/issues/1325
> fix: handle uncaught error on upload

- .github/workflows/deploy.2anki.net.yml
Closes: https://github.com/2anki/2anki.net/issues/1276
> build: use temporary build path

- package-lock.json
- package.json
>   chore: update axios

- src/controllers/SimpleUploadController.ts
- src/controllers/SimpleUploadController/SimpleUploadController.ts
- src/controllers/SimpleUploadController/createPackages.ts
- src/controllers/SimpleUploadController/createResponse.ts
- src/controllers/UploadController.ts
- src/lib/misc/GetUploadHandler.ts
- src/routes/SimpleUploadRouter.ts
- src/server.ts
- src/services/UploadService.ts
- src/usecases/uploads/GeneratePackagesUseCase.ts
This adds a new endpoint for retrieving only upload info. Will be used by @alpkaanaksu to provide a simple UI.
> feat: simple endpoint for getting uploads

- package-lock.json
- package.json
> chore: remove nanoid

- src/controllers/DownloadController.ts
- src/services/EmailService/templates/convert-link.html
Getting complaints of expired download links.
> feat: inform user when the download has expired

- .github/workflows/create-release.yml
> feat: add release action

- .github/workflows/create-release.yml
This reverts commit 3d64a28e5f0aa288f58414e7ec7790f4cca7225e.
> Revert "fix: remove npm token"

- src/lib/markdown.ts
- src/lib/parser/DeckParser.ts
- src/lib/parser/PrepareDeck.ts
- src/test/fixtures/Default 8e8a3abeb8d14f6a9fc3cb0d6c086ecb.html
- src/usecases/uploads/GeneratePackagesUseCase.ts
This will use the new Markdown fallback to create flashcards when there are no toggles.
> feat: allow for cloze deletions from paragraphs

- .github/workflows/deploy.2anki.net.yml
Hoping it fixes the issue where auto deploy from main keeps failing
> 2024/05/04 07:02:55 Error: can't connect without a private SSH key or password
> fix(deploy): add environment to deployment config

- src/data_layer/UsersRepository.ts
- src/lib/integrations/stripe.ts
This will reduce manual cleanup
> fix: lowercase emails

- src/controllers/UsersControllers.ts
- src/services/AuthenticationService.ts
Linked email check was not working as intended.
> fix: ensure the linked email is used for the lookup first

- src/controllers/UsersControllers.ts
- src/services/AuthenticationService.ts
- chore: log linked email
- fix: ensure the linked email is used for the lookup first
> fix: email issue (second attempt)

- src/controllers/UploadController.ts
- src/lib/misc/ErrorHandler.tsx
- src/lib/misc/isLimitError.test.ts
- src/lib/misc/isLimitError.ts
- src/services/UploadService.ts
> chore: do not log all of the limit errors

- src/lib/misc/ErrorHandler.tsx
- src/lib/misc/isEmptyPayload.tsx
No idea why someone would upload empty files but it happens.
> fix: skip the empty uploads

- src/controllers/UsersControllers.ts
- src/routes/UserRouter.ts
- src/services/AuthenticationService.ts
Relates-to: https://github.com/2anki/server/issues/937
> feat: login with Google

- src/controllers/SettingsController/SettingsController.test.ts
- src/controllers/SettingsController/supportedOptions.ts
- src/lib/parser/DeckParser.test.ts
- src/lib/parser/DeckParser.ts
- src/lib/parser/Settings/Settings.ts
- src/lib/parser/getFileContents.ts
- src/lib/parser/getHTMLContents.test.ts
- src/lib/parser/getTitleFromMarkdown.ts
- src/lib/parser/handleNestedBulletPointsInMarkdown.ts
- src/test/fixtures/empty-deck.md
- src/test/fixtures/simple-deck.md
- src/test/test-utils.ts
Related-to: https://github.com/2anki/server/issues/926
> feat: add support for bullet points in Markdown

- src/controllers/UsersControllers.ts
Fixes several errors in the logs.
> fix: do not assume getLocals is called by logged in users

- src/controllers/Upload/UploadController.test.ts
- src/controllers/Upload/UploadController.ts
- src/controllers/Upload/helpers/handleUploadLimitError.ts
- src/routes/UploadRouter.ts
- src/services/UploadService.ts
This should improve confusion experienced by new users.
> fix: redirect to login or pricing page

- src/controllers/NotionController.ts
- src/data_layer/NotionRespository.ts
- src/routes/NotionRouter.ts
- src/services/NotionService/NotionService.ts
Currently only possible by deleting account.
> feat: enable users to remove Notion connection

- src/controllers/IndexController/IndexController.ts
- src/lib/misc/getUploadLimits.ts
- src/routes/DefaultRouter.ts
- src/server.ts
- src/services/EmailService/EmailService.ts
> feat: add endpoint for contacting support

- src/data_layer/NotionRespository.ts
- src/services/NotionService/NotionService.ts
In the new UI there is a button to disconnect notion and that would
likely have increased these errors.
Closes: https://github.com/2anki/server/issues/1521
> fix: reduce errors caused by lack of Notion token

- migrations/20240820194742_add-feedback-table.js
- src/controllers/IndexController/IndexController.ts
- src/lib/storage/jobs/helpers/deleteOldUploads.ts
- src/routes/DefaultRouter.ts
This will enable people to report issues with examples.
> feat: persist user feedback until marked as resolved

- src/data_layer/UsersRepository.ts
This will be handled separately in the cleanup interval.
> fix: do not delete subs

- package-lock.json
- package.json
- src/controllers/SettingsController/SettingsController.test.ts
- src/controllers/SettingsController/supportedOptions.ts
- src/lib/anki/zip.tsx
- src/lib/parser/PrepareDeck.ts
- src/lib/parser/Settings/Settings.ts
- src/lib/parser/experimental/FallbackParser.ts
- src/lib/parser/experimental/VertexAPI/convertPDFToHTML.ts
- src/lib/storage/checks.ts
- src/usecases/uploads/allowPDFUpload.ts
- src/usecases/uploads/getPackagesFromZip.ts
- src/usecases/uploads/worker.ts
We are using the [Google Vertex AI API](https://cloud.google.com/vertex-ai/docs/reference/rest).
> feat: experimental pdf support

- src/lib/anki/zip.tsx
- src/usecases/uploads/getPackagesFromZip.ts
This fixes a bug where some Zip files can contain nested data.
> feat: allow nested zip files to be processed

- src/lib/parser/DeckParser.ts
- src/lib/parser/extractStyles.test.ts
- src/lib/parser/extractStyles.ts
- src/lib/parser/withFontSize.ts
Fixes a regression due to changes in the Notion style.
> fix: preserve the toggle rendering on the back

- src/controllers/SettingsController/SettingsController.test.ts
- src/controllers/SettingsController/supportedOptions.ts
- src/lib/parser/DeckParser.ts
- src/lib/parser/Settings/Settings.ts
- src/lib/parser/findToggles.ts
This is useful for creating cloze deletions on the front and reducing lots of unnecessary cards created.
> feat: new card option for disabling indented bullets

- src/lib/parser/DeckParser.ts
This fixes the issue where images are missing on bullet points.
> fix: ensure media is embedded both for front and back

- src/lib/parser/DeckParser.ts
- src/lib/parser/PrepareDeck.ts
- src/lib/parser/WorkSpace.ts
- src/lib/parser/exporters/embedFile.ts
- src/lib/parser/pdf/convertPDFToImages.ts
- src/lib/storage/checks.ts
- src/usecases/uploads/allowPDFUpload.ts
- src/usecases/uploads/getPackagesFromZip.ts
- src/usecases/uploads/isZipContentFileSupported.ts
- src/usecases/uploads/worker.ts
Closes: https://github.com/2anki/server/issues/1471
> feat: Support PDF file uploads

- src/lib/parser/PrepareDeck.ts
This will reduce disk storage.
> perf: do not write out pdf content to html file

- src/controllers/SettingsController/SettingsController.test.ts
- src/controllers/SettingsController/supportedOptions.ts
- src/lib/parser/PrepareDeck.ts
- src/lib/parser/Settings/Settings.ts
- src/lib/parser/experimental/VertexAPI/constants.ts
- src/lib/parser/experimental/VertexAPI/convertImageToHTML.ts
- src/lib/storage/checks.ts
- src/lib/zip/zip.tsx
- src/usecases/uploads/getPackagesFromZip.ts
- src/usecases/uploads/worker.ts
Related-to: https://github.com/2anki/server/issues/1156
> feat: convert images to flashcards

- src/lib/pdf/ConvertPPTToPDF.ts
> fix: use uconv

- package-lock.json
- src/lib/debug/perserveFilesForDebugging.ts
- src/lib/storage/checks.ts
We want to allow for uploading incomplete Google Chrome downloads.
> feat: add support for uploading Google Chrome downloads

- src/lib/anki/CardGenerator.ts
- src/lib/parser/PrepareDeck.ts
- src/lib/pdf/ConvertPPTToPDF.ts
- src/lib/pdf/convertPDFToImages.ts
- src/lib/pdf/convertPage.ts
- src/lib/pdf/getPageCount.ts
> perf: allow for more buffers to be passed between children processes

- .github/workflows/stale_bot.yml
> chore(github): add stalebot

- src/lib/storage/jobs/ConversionJob.ts
It's causing a lot of noise for big uploads.
> fix: skip empty decks

- package-lock.json
- src/controllers/NotionController.ts
This will reduce spam error in the logs.
> fix: check connection link before searching

- src/routes/ki/KiRouter.ts
- src/templates/ki.html
> fix: get file stuff working again

- migrations/20231001_create_sessions_table.js
- src/data_layer/SessionRepository.ts
- src/routes/ki/KiRouter.ts
- src/routes/ki/handlePartialJson.ts
> chore: debug

- src/templates/ki.html
> fix: use less padding on mobile

- src/data_layer/SessionRepository.ts
- src/routes/ki/KiRouter.ts
- src/templates/ki.html
- **fix: use less padding on mobile**
- **feat: move everything to the bottom of the page**
- **feat: improve for mobile**
> improvements to the mobile from testing

- src/data_layer/SessionRepository.ts
- src/routes/ki/KiRouter.ts
- src/templates/ki.html
> feat: get session switching working

- src/templates/ki.html
> feat: improve mobile buttons

- src/controllers/UsersControllers.ts
- src/routes/middleware/RequireAuthentication.ts
> chore: add logging for locals issue

- src/controllers/UsersControllers.ts
> fix: overwrite locals.subscriber

- src/controllers/UsersControllers.ts
> fix: use cookie to get user

- src/controllers/UsersControllers.ts
- src/routes/middleware/configureUserLocal.ts
- src/services/AuthenticationService.ts
> chore: debug x

- src/services/AuthenticationService.ts
> chore: log more

- src/controllers/UsersControllers.ts
- src/services/AuthenticationService.ts
> fix: bug due to email linking issue

- src/controllers/UsersControllers.ts
- src/routes/ki/KiRouter.ts
- src/templates/ki.html
> fix: get the scroll working for really long results

- src/services/NotionService/NotionAPIWrapper.ts
> chore: use unique id for search time stamping

- src/services/NotionService/NotionAPIWrapper.ts
> Revert "chore: use unique id for search time stamping"

- src/controllers/UsersControllers.ts
> chore: disable kiui for now

- src/lib/storage/jobs/helpers/updateStripeSubscriptions.ts
Will be used to resolve stale subscription state.
> fix: ensure database connection is properly closed after subscription sync

- src/infrastracture/adapters/fileConversion/PrepareDeck.ts
- src/infrastracture/adapters/fileConversion/constants.ts
- src/infrastracture/adapters/fileConversion/convertPDFToHTML.ts
- src/lib/parser/Settings/CardOption.ts
This will let the users tune the output for PDF.
> feat: allow user to add instructions to vertex ai

- package-lock.json
- package.json
- src/data_layer/UsersRepository.ts
- src/routes/DefaultRouter.ts
- src/routes/middleware/configureUserLocal.ts
- src/routes/middleware/ensureIsLoggedIn.ts
- src/services/AuthenticationService.ts
Also send more subscription info to frontend. Will reduce support emails.
> fix: follow ups after Express upgrade
