src/pages/upload-page.imba

- Changed the background to gray before
- Background turns green
- "Click to Upload..." is changed to "File Selected"
- File name gets displayed

Added the file selected indicator

---

src/components/n2a-header.imba

I fixed the focus issue of the create button in the navbar.
Fixed #125 (Create button in the navbar doesn't look good on focus.)
Now it looks just like the other navbar items when focused.

Fixed focus issue in header

---

README.md

I added:
- Alexander Alemayhu
- Alp Kaan Aksu
- Mads Cordes
These people can also be added:
- Abi for ideas 🤔 and videos 📹
- Boni for videos 📹
- Guillem Palausalva has also contributed some things (afaik)
I couldn't add those contributors due to the lack of necessary information.

Started the all-contributors table.

---

src/pages/useful-links.imba

Fixed a typo (Refferals → Referrals).
I pointed this out in 
a previous Zoom meeting.
_Please label as **hacktoberfest-accepted**, thanks 🙏🏻_

Fixed the refferals typo

---

src/components/n2a-footer.imba

I updated the footer to look better and include more content that's useful.
The old footer:
The updated footer:
closes #174

Footer improvement

---

src/server/templates/custom.css

I saw what people were complaining about. 90% is too big for AnkiDroid. If you change it to 80% everything works fine.
Leave it like this for some time. If people continue to complain, I'll update the custom CSS to be more minimal and compatible. But I still think 80% max-width will solve the problem.

Change max-width from 90% to 80%

---

src/server/parser/deck.imba
test/fixtures/Global Tag Support.html
test/test_global_tags.imba

Users can now include strikethrough text outside of toggle lists to create top-level global tags.
Closes #212 
<hr>

Add global tag support

---

src/components/n2a-header.imba

This lets us append a dev icon if this is the case (aka dev.2anki.net).
Have only tested this on my localhost, but it hopefully woks on the sever.
File(s) edited:
n2a-header.imba
Wasn't sure if this should have been kept in a separate file or not.

Added a way to check if the current URL is dev.2anki.net or not. issue#257

---

web/src/components/Footer.tsx

Just saw and fixed a type in the footer:
a open source -> aN open source

Fixed a typo in footer

---

server/parser/DeckParser.ts

- Removed mp3 url box from card.back, including the remaining empty figure
- I tried it, the mp3 file can still be played. 
Fixes #82

removed mp3 url from cards

---

server/parser/DeckParser.ts

Need to check if this is a potential regression but seems to work as
expected based on user sample.

server/parser: fix bug where nested images got ignored

---

web/_redirects
web/src/components/Footer.tsx
web/src/pages/Home.tsx

They must have broken after enabling the custom subdomains on Notion. 
Thanks to Esry on Discord reporting it.

fix broken wiki links

---

.github/workflows/server-tests.yml
server/genanki/requirements.txt

Unfortunately we have to lock the `setuptools` versions. Newer ones are causing build errors.

Get integration tests passing

---

server/knexfile.ts
server/package.json
server/server.ts

It turns out that the environment variables are not available during
build time. So we need to run the migrations later when we actually have
the environment during run time.

server: run migrations programmatically

---

server/knexfile.ts

The current working directory is different. We can't rely on it being
relative.

server: use MIGRATIONS_DIR if set

---

Dockerfile

Fixes:
```
remote: > notion2anki-server@0.7.11 build
remote: > tsc -p .
remote:
remote: sh: 1: tsc: not found
remote: The command '/bin/sh -c npm --prefix /app/server run build' returned a non-zero code: 127
remote: 2021/12/12 03:40:31 exit status 127
```

Dockerfile: make sure tsc and ts-node are installed globally

---

web/src/components/input/Switch.tsx
web/src/pages/Home.tsx
web/src/pages/SearchPage.tsx

I kept hitting the error
> Cannot read properties of undefined (reading 'owner')
Turns out we have made assumptions regarding the owner. I suspect what happens is the following
i) user logins (everything works due to valid token)
ii) user logins to a second computer (everything works fine due to new token)
iii) user returns to the previous computer (stops working due to invalidated token)
Hopefully, this is resolved now by asking the user to log in again.
The other changes are rewording front page and misc cleanup.

Fix stuck in a loop where search stops working 

---

web/src/components/Dashboard/DefineRules.tsx

Probably more bugs hidden in there but now the indentation of bullet lists creates flashcards again.

Getting the bullest lists working again

---

web/src/components/Footer.tsx

It's currently a broken image. Don't know when this regression happened, it was working before.

web/footer: fix broken link for scrimba logo

---

web/package-lock.json
web/package.json
web/src/components/Dashboard/SearchObjectEntry.tsx
web/src/components/Dashboard/UploadObjectEntry.tsx
web/src/components/modals/SettingsModal.tsx
web/src/lib/Backend.ts

Closes: https://github.com/alemayhu/2anki.net/issues/428

Add support for custom icons

---

.github/workflows/deploy.2anki.net.yml

This should prevent multiple deploys when merging low hanging fruit pull
request before all actions finish.

github/workflows: limit deployment to one instance

---

web/config-overrides.js

This is to address a sonar code smell:
> "switch" statements should have at least 3 "case" clauses

refactor: use conditional statement instead of switch

---

Makefile

The diff here won't show everything but there is a private `main` and previously there was `stable` branch for the server submodule. The server submodule will be phased out soon and it will be changed into a regular directory with all of the code being public.

Synchronize the main branch to use main branch in the server (git submodule)

---

.github/workflows/server-tests.yml

It won't work due to environment secrets unavailable.

chore: do not run server tests on dependabot pull requests

---

.github/workflows/auto-bump-version.yml

Hopefully fixes the following issue
```
2022-04-11T20:05:44.9667178Z (node:1614) UnhandledPromiseRejectionWarning: Error: package.json could not be found in your project's root.
2022-04-11T20:05:44.9668877Z     at getPackageJson (/home/runner/work/_actions/phips28/gh-action-bump-version/master/index.js:211:41)
2022-04-11T20:05:44.9670129Z     at /home/runner/work/_actions/phips28/gh-action-bump-version/master/index.js:16:15
2022-04-11T20:05:44.9670833Z     at Object.<anonymous> (/home/runner/work/_actions/phips28/gh-action-bump-version/master/index.js:207:3)
2022-04-11T20:05:44.9671291Z     at Module._compile (internal/modules/cjs/loader.js:999:30)
2022-04-11T20:05:44.9671844Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2022-04-11T20:05:44.9672224Z     at …
```

fix: set PACKAGEJSON_DIR for release bumping

---

server/genanki/create_deck.py
server/genanki/requirements.txt

We want to track the errors in here.

chore: add Sentry error reporting to the create_deck script

---

.sonarcloud.properties

Hopefully fixes false positives.

chore: exclude templates and test fixtures from Sonar

---

server/lib/anki/getDeckname.test.ts
server/lib/anki/getDeckname.ts
server/lib/notion/BlockHandler.ts

fix: fix duplicate deck names

---

server/lib/notion/BlockHandler.ts
server/lib/notion/blocks/BlockChildPage.tsx
server/lib/notion/blocks/LinkToPage.tsx
server/lib/notion/blocks/lists/BlockTodoList.tsx
server/lib/notion/blocks/media/BlockEmbed.tsx
server/lib/notion/blocks/media/BlockVideo.tsx
server/lib/notion/helpers/getBlockId.test.ts
server/lib/notion/helpers/getBlockId.ts
server/lib/notion/helpers/getListItems.tsx
server/lib/notion/helpers/renderLink.tsx
server/lib/parser/DeckParser.ts
server/lib/parser/helpers/getYouTubeEmbedLink.ts
server/lib/parser/helpers/getYouTubeID.ts

also misc follow up issues for lists.

feat: link to page

---

server/package-lock.json
server/package.json
server/routes/upload/helpers/TriggerUnsupportedFormat.ts
server/routes/upload/helpers/handleUpload.ts

We might bring it back but regardless there is fallback in place so we
don't need to this to throw error in production.

chore: remove old error message for Markdown support

---

server/lib/email/EmailHandler.ts
server/lib/parser/ParserRules.ts
server/package-lock.json
server/package.json
server/routes/notion/convert/helpers/performConversion.ts
server/routes/users/index.ts
web/src/lib/Backend.ts
web/src/pages/Search/components/DefineRules.tsx

Small meaning less than what is the max size in an email.

fix: allow users to request email notification for "small" uploads

---

server/lib/misc/ErrorHandler.ts
server/templates/error-message.html

The clients will no longer treat it as HTML.

refactor: use plain text for error messages

---

package-lock.json
package.json
src/lib/notion/BlockHandler.ts
src/lib/notion/helpers/getSubDeckName.test.ts
src/lib/notion/helpers/getSubDeckName.ts

We can't assume that the block is a text-like block. So we need to
either use a top-level title or title nested in properties.
Fixes: https://github.com/2anki/server/issues/696

fix: handle bug where child page titles would cause crash

---

src/routes/upload/helpers/handleUpload.ts

Users still see a message and can get to the settings.

fix: do not throw on empty package

---

src/routes/users/index.ts

fix: do not require auth for /is-patreon call

---

.github/workflows/deploy.2anki.net.yml

This fixes current deployment failures to production
> 2022-12-25T09:03:18.8375118Z fatal: detected dubious ownership in repository at '/github/workspace'
2022-12-25T09:03:18.8375726Z To add an exception for this directory, call:
2022-12-25T09:03:18.8375926Z
2022-12-25T09:03:18.8376189Z 	git config --global --add safe.directory /github/workspace
2022-12-25T09:03:18.8392298Z fatal: detected dubious ownership in repository at '/github/workspace'
2022-12-25T09:03:18.8392682Z Default is master
2022-12-25T09:03:18.8397015Z To add an exception for this directory, call:
2022-12-25T09:03:18.8397225Z
2022-12-25T09:03:18.8397504Z 	git config --global --add safe.directory /github/workspace
2022-12-25T09:03:18.8397947Z Disabling host key checking
2022-12-25T09:03:18.8398302Z The deploy is starting …

fix: update dokku-github-action from v7.0 to v7.1

---

package-lock.json
package.json
src/routes/favorite/getFavorites.ts

We can get into a timeout with the Notion API due to lack of access or simply the page being deleted. In that case we purge all of the users favorites.

fix: prevent favorites from crashing server

---

Dockerfile
package-lock.json
package.json
src/server.ts

We need it early due to storage layer initializing AWS.

chore: move loading of env file before imports

---

src/routes/VersionRouter.ts

Fixes Sentry crash report:
> Cannot read properties of undefined (reading 'service')

fix: pass the request and response correctly

---

.github/workflows/build-server.yml

Fixing build warning
> [build (16.15.1)](https://github.com/2anki/2anki.net/actions/runs/5551982487/jobs/10138753908)
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-node@v1.

chore: Update GitHub Actions checkout version

---

src/data_layer/NotionRespository.ts

Trying again to resolve the token exception in Sentry:
> TypeError
>
> POST /api/notion/pages
>
> Unhandled
> Cannot read properties of undefined (reading 'token')

fix(data_layer): Throw error if Notion token is not found

---

src/lib/storage/jobs/helpers/runCleanup.ts

We need this temporarily for a server migration. Replicated servers
should not cleanup since they don't have all the data tables to
determine if files are too old.

chore: add check env for skipping cleanup

---

package-lock.json
package.json
src/controllers/UploadController.ts
src/services/UploadService.ts
src/usecases/uploads/GeneratePackagesUseCase.ts

Previously we were uploading them to the spaces and then retrieving one
file at a time. This can slow down the conversion process a lot.

feat: reduce bucket round-trip for uploads

---

src/lib/parser/DeckParser.ts
src/lib/parser/exporters/embedFile.ts
src/lib/storage/checks.ts
src/usecases/uploads/GeneratePackagesUseCase.ts

While at it remove Bugsnag breadcrumbs they are [not supported in Node.js.](https://github.com/bugsnag/bugsnag-js/issues/1223)

fix: leave Base64 images untouched

---

src/lib/parser/exporters/embedFile.ts

After reviewing several bug reports in Bugsnag and reproducing.
It's possible to export a page in Notion without the images

fix: downgrade the missing relative path

---

.github/dependabot.yml

No need to merge and deploy them seperately

build(dependabot): group dev dependencies

---

src/usecases/uploads/GeneratePackagesUseCase.ts

Currently not possible to upload just CSV files.

fix: add csv to supported file type uploads

---

src/lib/misc/ErrorHandler.tsx

We are getting some very low quality bug reports from people not
spending time to learn how 2anki.net works.

fix: remove GitHub link from the no package error

---

src/lib/parser/DeckParser.ts

These are coming directly from Notion. No idea why they are doing it
this way. It was not like this before. What basically happens is that
our `preserveNewlinesIfApplicable` function will add `<br />` to the tag
and it will totally break the KaTex.
Fixes: https://github.com/2anki/2anki.net/issues/1382

fix: do not add empty lines in the path `d` attribute

---

src/usecases/uploads/GeneratePackagesUseCase.ts

Fixes:
The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

fix: handle file.path is not for buffer

---

src/lib/parser/DeckParser.test.ts
src/lib/parser/Settings/Settings.ts

Resolves issue where cards are accidentally reversed.

fix: do not enable reversed cards when missing settings

---

src/controllers/StripeController/StripeController.ts
src/controllers/StripeController/extractTokenFromCookies.ts
src/controllers/Upload/UploadController.test.ts
src/controllers/Upload/UploadController.ts
src/controllers/Upload/helpers/handleUploadLimitError.ts
src/data_layer/UsersRepository.ts
src/routes/UploadRouter.ts
src/routes/WebhookRouter.ts
src/services/AuthenticationService.ts
src/services/UploadService.ts
src/services/UsersService.ts

Connect the payer session with the currently logged in user.

fix: match payer email with registered email

---

package.json
src/lib/parser/DeckParser.ts
src/lib/parser/PrepareDeck.ts
src/test/test-utils.ts
src/usecases/uploads/GeneratePackagesUseCase.ts
src/usecases/uploads/getPackagesFromZip.ts
src/usecases/uploads/worker.ts

- Offload flashcard generation to a separate worker thread
- Prevents blocking of main thread during uploads, improving responsiveness
- Addresses bug causing server slowdown during large uploads
Refs:
https://nodejs.org/api/worker_threads.html
https://stackoverflow.com/questions/61095741/how-do-i-avoid-blocking-an-express-rest-service

feat: Implement worker threads for upload processing

---

src/lib/User/checkFlashcardsLimits.ts
src/lib/User/checkLimits.test.ts

This fixes a regression where limits were enforced wrongly.

fix: handle paying field is undefined

---

src/lib/parser/experimental/FallbackParser.ts

fix: ensure undefined values are removed in cleanup

---

src/lib/parser/helpers/handleClozeDeletions.test.ts
src/lib/parser/helpers/handleClozeDeletions.ts

This fixes a bug where bullet points with no prefix would get grouped
into previous bullets.

fix: ensure existing cloze are accounted for to pick the next auto number

---

src/lib/storage/checks.ts
src/usecases/uploads/worker.ts

A file is considered a potential zip file if it does not contain a
period.  Since zip files are not named with a period, but it is possible
to upload such files using drag and drop.

fix: allow for zip uploads without suffix

---

src/lib/storage/checks.test.ts
src/lib/storage/checks.ts
src/usecases/uploads/worker.ts

Fixes the following crash:
> 2024-12-04T13:06:45.039Z - TypeError:
> Cannot read properties of undefined (reading 'trim')
> TypeError: Cannot read properties of undefined (reading 'trim')

fix: handle no filename in zip check

---

src/lib/parser/Settings/loadSettingsFromDatabase.ts

I got a bug report where wrong settings where being applied and after debugging further the saved payload was never used due to the nested data.

fix: ensure the payload is passed into the setting

---

src/usecases/uploads/isZipContentFileSupported.ts
src/usecases/uploads/worker.ts

It's currently unreliable and the output produces clipped images.

fix: ignore PPT in zip

---

src/lib/parser/exporters/embedFile.ts

I am hoping this will resolve some bugs where re-importing the same page
is causing the wrong images to show up on the wrong toggles.

fix: use the file contents when creating unique file name

---

src/lib/parser/DeckParser.ts
src/lib/parser/PrepareDeck.ts
src/lib/parser/experimental/FallbackParser.ts
src/lib/parser/experimental/VertexAPI/convertImageToHTML.ts
src/lib/parser/experimental/VertexAPI/removeFirstAndLastLine.ts
src/usecases/uploads/isZipContentFileSupported.ts

This is backwards compatible and should only trigger with the
imageQuizHtmlToAnki card option.

fix: resolve crash caused by images being overwritten with HTML

---

src/lib/pdf/ConvertPPTToPDF.ts

We can get bad exit code for warnings.

fix: do not fail due to unoconv exit code

---

src/lib/extractDeckName.test.ts
src/lib/extractDeckName.ts
src/lib/parser/Deck.ts
src/lib/parser/DeckParser.ts

We are just stripping it away since it causes the export to produce
file names with newlines.

fix: support pages with newlines in title

---

src/lib/zip/zip.tsx
src/usecases/uploads/getPackagesFromZip.ts
src/usecases/uploads/isZipContentFileSupported.ts

Initially I was worried that the Vertex AI usage could trigger too many requests in Google cloud but from testing I can see that Google has rate limiting in place so it will likely be triggered if batch zip with vertex enabled.

fix: allow PDF files in zip uploads

---

package-lock.json
src/services/NotionService/BlockHandler/BlockHandler.ts

In the previous implementation it was overwriting resulting in only one
deck.

fix: ensure handleChildDatabase picks up all decks

---

package-lock.json
src/lib/storage/checks.test.ts
src/lib/storage/checks.ts
src/routes/ki/KiRouter.ts
src/usecases/uploads/worker.ts

Renamed isPotentialZipFile to isCompressedFile and added explicit detection of .z file extensions while maintaining backward compatibility through aliasing.

feat(checks): Enable support for Unix compress (.z) files

---

src/controllers/CardOptionsController/CardOptionsController.test.ts
src/controllers/CardOptionsController/supportedOptions.ts
src/infrastracture/adapters/fileConversion/PrepareDeck.ts
src/infrastracture/adapters/fileConversion/convertPDFToImages.ts
src/lib/parser/Settings/CardOption.ts
src/lib/zip/zip.tsx

This feature allows users to skip PDF processing by setting process-pdfs=false, addressing performance concerns when handling ZIP files containing PDFs.
Key changes:
- Add processPDFs boolean property to CardOption class
- Add process-pdfs to supported options with default true
- Update PDF processing logic in PrepareDeck and convertPDFToImages
- Add early return in ZipHandler for PDFs when processing is disabled

feat: add process-pdfs option to control PDF processing

---

src/lib/parser/experimental/FallbackParser.test.ts
src/lib/parser/experimental/FallbackParser.ts

Fixes the following report:
>TypeError: Cannot read properties of undefined (reading 'load')
at FallbackParser.htmlToTextWithNewlines (/home/alemayhu/src/github.com/2anki/2anki.net/src/lib/parser/experimental/FallbackParser.js:19:37)
at FallbackParser.run (/home/alemayhu/src/github.com/2anki/2anki.net/src/lib/parser/experimental/FallbackParser.js:107:40)
at DeckParser.tryExperimental (/home/alemayhu/src/github.com/2anki/2anki.net/src/lib/parser/DeckParser.js:447:33)
at /home/alemayhu/src/github.com/2anki/2anki.net/src/infrastracture/adapters/fileConversion/PrepareDeck.js:97:43
at Generator.next (<anonymous>)
at /home/alemayhu/src/github.com/2anki/2anki.net/src/infrastracture/adapters/fileConversion/PrepareDeck.js:8:71
at new Promise (<anonymous>)
at __awaiter …

fix: use correct import for cheerio

---

src/data_layer/JobRepository.ts

Previously the deletion would fail since the id and object_id do not
match.

fix: use correct id for deleting jobs

---

scripts/digitalocean/dump.ts

Add import.meta.url and fileURLToPath to properly resolve __dirname in ES module context. This fixes the migration failure when creating database dumps.

fix: resolve __dirname undefined error in ES modules

---

src/data_layer/index.ts

- Add INSTANCE_ID environment variable check
- Only run ScheduleCleanup on main instance
- Prevents race conditions between instances

feat: disable cleanup jobs on Singapore instance to prevent conflicts
